---
urn:node:ARCTIC:
  CN_date_deprecated: null
  CN_date_operational: 2016-12-01T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/ARCTIC.png
  CN_node_name: Arctic Data Center
  CN_operational_status: operational
urn:node:BCODMO:
  CN_date_deprecated: null
  CN_date_operational: 2016-11-29T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/BCODMO.png
  CN_node_name: Biological and Chemical Oceanography Data Management Office (BCO-DMO)
  CN_operational_status: operational
urn:node:CDL:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/CDL.png
  CN_node_name: Merritt Repository
  CN_operational_status: operational
urn:node:CLOEBIRD:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:DRYAD:
  CN_date_deprecated: null
  CN_date_operational: 2014-02-22T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/DRYAD.png
  CN_node_name: Dryad Digital Repository
  CN_operational_status: operational
urn:node:EDACGSTORE:
  CN_date_deprecated: null
  CN_date_operational: 2014-06-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/EDACGSTORE.png
  CN_node_name: Earth Data Analysis Center (EDAC)
  CN_operational_status: operational
urn:node:EDORA:
  CN_date_deprecated: null
  CN_date_operational: 2014-11-24T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/EDORA.png
  CN_node_name: Environmental Data for the Oak Ridge Area
  CN_operational_status: operational
urn:node:ESA:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/ESA.png
  CN_node_name: ESA Data Registry
  CN_operational_status: operational
urn:node:GLEON:
  CN_date_deprecated: null
  CN_date_operational: 2015-03-10T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/GLEON.png
  CN_node_name: Global Lake Ecological Observatory Network (GLEON)
  CN_operational_status: operational
urn:node:GOA:
  CN_date_deprecated: null
  CN_date_operational: 2013-11-15T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/GOA.png
  CN_node_name: Gulf of Alaska Data Portal
  CN_operational_status: operational
urn:node:GRIIDC:
  CN_date_deprecated: null
  CN_date_operational: 2017-01-20T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/GRIIDC.png
  CN_node_name: Gulf of Mexico Research Initiative
  CN_operational_status: operational
urn:node:GULFWATCH:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: null
urn:node:IARC:
  CN_date_deprecated: null
  CN_date_operational: 2015-05-08T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/IARC.png
  CN_node_name: International Arctic Research Center (IARC) Data Archive
  CN_operational_status: operational
urn:node:IOE:
  CN_date_deprecated: null
  CN_date_operational: 2014-08-13T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/IOE.png
  CN_node_name: Montana IoE Data Repository
  CN_operational_status: operational
urn:node:KNB:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/KNB.png
  CN_node_name: Knowledge Network for Biocomplexity
  CN_operational_status: operational
urn:node:KUBI:
  CN_date_deprecated: null
  CN_date_operational: 2014-02-20T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/KUBI.png
  CN_node_name: University of Kansas - Biodiversity Institute
  CN_operational_status: operational
urn:node:LTER:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/LTER.png
  CN_node_name: LTER Network Member Node
  CN_operational_status: operational
urn:node:LTER_EUROPE:
  CN_date_deprecated: null
  CN_date_operational: 2014-06-18T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/LTER_EUROPE.png
  CN_node_name: Europe Long-Term Ecosystem Research Network (LTER Europe)
  CN_operational_status: operational
urn:node:NCEI:
  CN_date_deprecated: null
  CN_date_operational: 2016-03-31T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/NCEI.png
  CN_node_name: NOAA NCEI Oceanographic Data Archive
  CN_operational_status: operational
urn:node:NEON:
  CN_date_deprecated: null
  CN_date_operational: 2016-07-13T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/NEON.png
  CN_node_name: National Ecological Observatory Network
  CN_operational_status: operational
urn:node:NKN:
  CN_date_deprecated: null
  CN_date_operational: 2016-06-28T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/NKN.png
  CN_node_name: Idaho Northwest Knowledge Network
  CN_operational_status: operational
urn:node:NMEPSCOR:
  CN_date_deprecated: null
  CN_date_operational: 2015-05-27T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/NMEPSCOR.png
  CN_node_name: NM EPSCoR
  CN_operational_status: operational
urn:node:NRDC:
  CN_date_deprecated: null
  CN_date_operational: 2015-12-21T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/NRDC.png
  CN_node_name: Nevada Research Data Center
  CN_operational_status: operational
urn:node:ONEShare:
  CN_date_deprecated: null
  CN_date_operational: 2012-10-02T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/ONEShare.png
  CN_node_name: ONEShare Repository
  CN_operational_status: operational
urn:node:ORNLDAAC:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/ORNLDAAC.png
  CN_node_name: ORNL DAAC
  CN_operational_status: operational
urn:node:PISCO:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/PISCO.png
  CN_node_name: PISCO MN
  CN_operational_status: operational
urn:node:PPBIO:
  CN_date_deprecated: null
  CN_date_operational: 2016-05-17T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/PPBIO.png
  CN_node_name: Programa de Pesquisa em Biodiversidade (PPBio)
  CN_operational_status: operational
urn:node:R2R:
  CN_date_deprecated: null
  CN_date_operational: 2017-01-18T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/R2R.png
  CN_node_name: Rolling Deck to Repository (R2R)
  CN_operational_status: operational
urn:node:RGD:
  CN_date_deprecated: null
  CN_date_operational: 2014-11-24T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/RGD.png
  CN_node_name: Regional and Global Biogeochemical Dynamics Data (RGD)
  CN_operational_status: operational
urn:node:SANPARKS:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/SANPARKS.png
  CN_node_name: SANParks Data Repository
  CN_operational_status: operational
urn:node:SEAD:
  CN_date_deprecated: null
  CN_date_operational: 2013-12-18T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/SEAD.png
  CN_node_name: SEAD Virtual Archive
  CN_operational_status: operational
urn:node:TDAR:
  CN_date_deprecated: null
  CN_date_operational: 2017-01-25T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/TDAR.png
  CN_node_name: the Digital Archaeological Record
  CN_operational_status: operational
urn:node:TERN:
  CN_date_deprecated: null
  CN_date_operational: 2015-06-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/TERN.png
  CN_node_name: Terrestrial Ecosystem Research Network
  CN_operational_status: operational
urn:node:TFRI:
  CN_date_deprecated: null
  CN_date_operational: 2013-06-18T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/TFRI.png
  CN_node_name: Taiwan Forestry Research Institute
  CN_operational_status: operational
urn:node:USANPN:
  CN_date_deprecated: null
  CN_date_operational: 2014-01-28T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/USANPN.png
  CN_node_name: USA National Phenology Network
  CN_operational_status: operational
urn:node:USGSCSAS:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:USGS_SDC:
  CN_date_deprecated: null
  CN_date_operational: 2015-11-12T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/USGS_SDC.png
  CN_node_name: USGS Science Data Catalog
  CN_operational_status: operational
urn:node:US_MPC:
  CN_date_deprecated: null
  CN_date_operational: 2014-12-22T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/US_MPC.png
  CN_node_name: Minnesota Population Center (MPC)
  CN_operational_status: operational
urn:node:mnORC1:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: DataONE ORC Dedicated Replica Server
  CN_operational_status: replicator
urn:node:mnORC2:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:mnUCSB1:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: DataONE UCSB Dedicated Replica Server
  CN_operational_status: replicator
urn:node:mnUNM1:
  CN_date_deprecated: null
  CN_date_operational: 2012-07-23T00:00:0.000Z
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: DataONE UNM Dedicated Replica Server
  CN_operational_status: replicator
urn:node:mnUNM2:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated

