---
urn:node:ARCTIC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:BCODMO:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:CDL:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:CLOEBIRD:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:DRYAD:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:EDACGSTORE:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:EDORA:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:ESA:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:GLEON:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:GOA:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:GRIIDC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:GULFWATCH:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: null
urn:node:IARC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:IOE:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:KNB:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:KUBI:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:LTER:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:LTER_EUROPE:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:NCEI:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:NEON:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:NKN:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:NMEPSCOR:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:NRDC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:ONEShare:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:ORNLDAAC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:PISCO:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:PPBIO:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:R2R:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:RGD:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:SANPARKS:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:SEAD:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:TDAR:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:TERN:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:TFRI:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:USANPN:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:USGSCSAS:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:USGS_SDC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:US_MPC:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: operational
urn:node:mnORC1:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: replicator
urn:node:mnORC2:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated
urn:node:mnUCSB1:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: replicator
urn:node:mnUNM1:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: replicator
urn:node:mnUNM2:
  CN_date_deprecated: null
  CN_date_operational: null
  CN_date_upcoming: null
  CN_info_url: null
  CN_logo_url: null
  CN_node_name: null
  CN_operational_status: deprecated

